### ISSUE TITLE
Release for 8.14.0

### ISSUE THREAD

**Issue by roptat** [coq-community/semantics#8]
Hi!

as you might know, we now have coq-semantics in guix, thanks to Simon. I was trying to update coq to 8.14.0 and after updating other packages, this is the last package in guix, whose latest release still fails with the new version of coq. I managed to build the latest commit with coq 8.14.0 without issues. Do you have any plan to make a new release for coq 8.14.0? Any timeline?

Thanks!

**Comment by k4rtik** [comment]
Hi @roptat thanks for bringing this issue to my attention. The release has been made and should be available through coq-released opam repo. Could you try again and let me know if things look okay at the guix end?

**Comment by roptat** [comment]
Thanks for being so quick! It seems to build and install properly. I'm not a user of this package. Is there a simple test I can do to check it works fine?

**Comment by k4rtik** [comment]
If it builds and installs, that should be good enough. Thanks for checking.
